// FETCH MOVIES
export const MOVIES_LOADING = 'MOVIES_LOADING'
export const FETCH_MOVIES = 'FETCH_MOVIES'
export const MOVIES_FAILED = 'MOVIES_FAILED'
//FETCH FAVORITES
export const FAVORITES_LOADING = 'FAVORITES_LOADING'
export const FETCH_FAVORITES = 'FETCH_FAVORITES'
export const FAVORITES_FAILED = 'FAVORITES_FAILED'
export const ADD_FAVORITE = 'ADD_FAVORITE'
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'
//FETCH COMMENTS
export const ADD_COMMENT = 'ADD_COMMENT'
export const FETCH_COMMENTS = 'FETCH_COMMENTS'
export const COMMENTS_FAILED = 'COMMENTS_FAILED'

export const REQUEST_DELETE = 'REQUEST_DELETE'
export const DELETE_COMMENT = 'DELETE_COMMENT'
// AUTHENTICATE USER
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
//SIGN UP
export const REQUEST_SIGNUP = 'REQUEST_SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'
